### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by CC007** [joel-costigliola/assertj-assertions-generator-maven-plugin#112] opened 2024-04-12 09:38 UTC
I see that in the past 4 years there hasn't been any work done on the project. Issues aren't responded to and user-made and dependabot PRs aren't being merged. 

Is there any prospect on the repo being revived any time soon or is the project abandoned?

If it will be revived, could an estimate be given on when it will be picked up again?

If it's abandoned, I suggest for this to be added to the documentation, so that users aren't thinking they picked a nice tool, without realizing it's abandoned.

**Comment by scordio** [comment] 2024-04-12 10:24
See https://github.com/assertj/assertj-assertions-generator/issues/215#issuecomment-2051487647.

**Comment by scordio** [comment] 2024-07-28 09:49
Closing as duplicate of assertj/assertj-assertions-generator#215.

**Closed as not planned by scordio** 2024-07-28 09:49 UTC
